### Sentiment Analysis 

The 2,000 record IMDb movie review database is accessible through NLTK directly with
<pre>from nltk.corpus import movie_reviews</pre>

### Load the Data

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('moviereviews.tsv', sep='\t')
df

     label                                             review
0      neg  how do films like mouse hunt get into theatres...
1      neg  some talented actresses are blessed with a dem...
2      pos  this has been an extraordinary year for austra...
3      pos  according to hollywood movies made in last few...
4      neg  my first press screening of 1998 and already i...
...    ...                                                ...
1995   pos  i like movies with albert brooks , and i reall...
1996   pos  it might surprise some to know that joel and e...
1997   pos  the verdict : spine-chilling drama from horror...
1998   pos  i want to correct what i wrote in a former ret...
1999   pos  a couple of months ago , when i first download...

[2000 rows x 2 columns]

## Remove Blank Records (optional)

In [2]:
# REMOVE NaN VALUES AND EMPTY STRINGS:
df.dropna(inplace=True)
df

     label                                             review
0      neg  how do films like mouse hunt get into theatres...
1      neg  some talented actresses are blessed with a dem...
2      pos  this has been an extraordinary year for austra...
3      pos  according to hollywood movies made in last few...
4      neg  my first press screening of 1998 and already i...
...    ...                                                ...
1995   pos  i like movies with albert brooks , and i reall...
1996   pos  it might surprise some to know that joel and e...
1997   pos  the verdict : spine-chilling drama from horror...
1998   pos  i want to correct what i wrote in a former ret...
1999   pos  a couple of months ago , when i first download...

[1965 rows x 2 columns]

In [3]:
blanks = []  # start with an empty list

for i,lb,rv in df.itertuples():  # iterate over the DataFrame
    if type(rv)==str:            # avoid NaN values
        if rv.isspace():         # test 'review' for whitespace
            blanks.append(i)     # add matching index numbers to the list
            
blanks

[57,
 71,
 147,
 151,
 283,
 307,
 313,
 323,
 343,
 351,
 427,
 501,
 633,
 675,
 815,
 851,
 977,
 1079,
 1299,
 1455,
 1493,
 1525,
 1531,
 1763,
 1851,
 1905,
 1993]

In [4]:
df.drop(blanks, inplace=True)

In [5]:
len(df)

1938

In [6]:
df['label'].value_counts()

label
neg    969
pos    969
Name: count, dtype: int64

### Import `SentimentIntensityAnalyzer` and create an sid object

In [7]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()

### Use sid to append a `comp_score` to the dataset

In [8]:
df['scores'] = df['review'].apply(lambda review: sid.polarity_scores(review))

df['compound']  = df['scores'].apply(lambda score_dict: score_dict['compound'])

df['comp_score'] = df['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')

df.shape

(1938, 5)

### Perform a comparison analysis between the original `label` and `comp_score`

In [9]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [10]:
accuracy_score(df['label'],df['comp_score'])

0.6357069143446853

In [11]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.72      0.44      0.55       969
         pos       0.60      0.83      0.70       969

    accuracy                           0.64      1938
   macro avg       0.66      0.64      0.62      1938
weighted avg       0.66      0.64      0.62      1938

In [12]:
print(confusion_matrix(df['label'],df['comp_score']))

[[427 542]
 [164 805]]