# Redommendation systems

In [6]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.16.3 in c:\users\avunoorihinduvahini\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (1.17.0)
Requirement already satisfied: numpy>=2.3.5 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from mlxtend) (2.4.2)
Requirement already satisfied: pandas>=2.3.3 in c:\users\avunoorihinduvahini\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\avunoorihinduvahini\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in c:\users\avunoorihinduvahini\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\avunoorihinduvahini\appdata\local\programs\python\python313\lib\site-packages (from pandas>=2.3.3->mlxtend) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from pandas>=2.3.3->mlxtend) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\avunoorihinduvahini\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\avunoorihinduvahini\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 1.4/1.4 MB 6.6 MB/s  0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.24.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import silhouette_score

from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

## step 1: Load Dataset

In [8]:
df = pd.read_csv("tourism_dataset.csv")

print(df.head())
print(df.shape)
print(df.info())

     Location Country    Category  Visitors  Rating    Revenue  \
0  kuBZRkVsAR   India      Nature    948853    1.32   84388.38
1  aHKUXhjzTo     USA  Historical    813627    2.01  802625.60
2  dlrdYtJFTA  Brazil      Nature    508673    1.42  338777.11
3  DxmlzdGkHK  Brazil  Historical    623329    1.09  295183.60
4  WJCCQlepnz  France    Cultural    124867    1.43  547893.24

  Accommodation_Available
0                     Yes
1                      No
2                     Yes
3                     Yes
4                      No
(5989, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5989 entries, 0 to 5988
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Location                 5989 non-null   object
 1   Country                  5989 non-null   object
 2   Category                 5989 non-null   object
 3   Visitors                 5989 non-null   int64
 4   Rating                   5989 non-null   float64
 5   Revenue                  5989 non-null   float64
 6   Accommodation_Available  5989 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 327.7+ KB
None

## Step 2: Data Preprocessing

In [9]:
df = df.dropna()

df['Accommodation_Available'] = df['Accommodation_Available'].map({'Yes':1,'No':0})

In [10]:
df['text_features'] = df['Category'] + " " + df['Country']

print(df[['Location','text_features']].head())

     Location      text_features
0  kuBZRkVsAR       Nature India
1  aHKUXhjzTo     Historical USA
2  dlrdYtJFTA      Nature Brazil
3  DxmlzdGkHK  Historical Brazil
4  WJCCQlepnz    Cultural France

## step3: NLP Feature Extraction (TF-IDF)

Convert text into numerical vectors.

In [11]:
tfidf = TfidfVectorizer(stop_words='english')

X_text = tfidf.fit_transform(df['text_features'])

print(X_text.shape)

(5989, 13)

## step 4: Clustering Destinations

Use KMeans clustering to group similar tourist places.

In [12]:
kmeans = KMeans(n_clusters=6, random_state=42)

df['Cluster'] = kmeans.fit_predict(X_text)

print(df[['Location','Category','Cluster']].head())

     Location    Category  Cluster
0  kuBZRkVsAR      Nature        1
1  aHKUXhjzTo  Historical        0
2  dlrdYtJFTA      Nature        4
3  DxmlzdGkHK  Historical        3
4  WJCCQlepnz    Cultural        5

Example clusters:

In [14]:
# Cluster 0 -> Nature tourism
# Cluster 1 -> Cultural tourism
# Cluster 2 -> Historical places
# Cluster 3 -> Adventure tourism
# Cluster 4 -> Religious tourism
# Cluster 5 -> Urban tourism

## step 5:Evaluate Clustering

In [15]:
score = silhouette_score(X_text, df['Cluster'])

print("Silhouette Score:", score)

Silhouette Score: 0.17230916610708985

## step 6:Association Rules (Travel Patterns)

Simulate tourist travel transactions using categories.

In [16]:
#Nature → Cultural
#Historical → Cultural
#Nature → Adventure

In [17]:
transactions = df.groupby('Country')['Category'].apply(list)
transactions = transactions.tolist()

In [18]:
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

df_assoc = pd.DataFrame(te_array, columns=te.columns_)

In [19]:
frequent_items = apriori(df_assoc, min_support=0.1, use_colnames=True)

rules = association_rules(frequent_items, metric="confidence", min_threshold=0.5)

print(rules[['antecedents','consequents','support','confidence']])

      antecedents                                       consequents  support  \
0     (Adventure)                                           (Beach)      1.0
1         (Beach)                                       (Adventure)      1.0
2     (Adventure)                                        (Cultural)      1.0
3      (Cultural)                                       (Adventure)      1.0
4    (Historical)                                       (Adventure)      1.0
..            ...                                               ...      ...
597       (Beach)  (Urban, Adventure, Historical, Cultural, Nature)      1.0
598   (Adventure)      (Urban, Beach, Historical, Cultural, Nature)      1.0
599  (Historical)       (Urban, Beach, Adventure, Cultural, Nature)      1.0
600    (Cultural)     (Urban, Beach, Adventure, Historical, Nature)      1.0
601      (Nature)   (Urban, Beach, Adventure, Historical, Cultural)      1.0

     confidence
0           1.0
1           1.0
2           1.0
3           1.0
4           1.0
..          ...
597         1.0
598         1.0
599         1.0
600         1.0
601         1.0

[602 rows x 4 columns]

c:\Users\Avunoorihinduvahini\AppData\Local\Programs\Python\Python313\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

## step 7:Recommendation System

In [20]:
def recommend_destination(place):

    place_cluster = df[df['Location']==place]['Cluster'].values[0]

    recommendations = df[df['Cluster']==place_cluster]

    return recommendations[['Location','Category','Country','Rating']].head(5)

## step 8:Test Recommendation

In [21]:
recommend_destination(df['Location'].iloc[10])

      Location   Category    Country  Rating
0   kuBZRkVsAR     Nature      India    1.32
5   IKdhVWFKRc   Cultural      Egypt    2.19
8   OcCopAsiyJ   Cultural  Australia    4.10
9   pXDJPYzTeU  Adventure      India    1.98
10  dUCLjskBYA      Urban  Australia    4.20

## step 9:Improved Recommendation (Cluster + Rating)

In [23]:
def recommend_best(place):

    cluster = df[df['Location']==place]['Cluster'].values[0]

    rec = df[df['Cluster']==cluster]

    rec = rec.sort_values(by='Rating',ascending=False)

    return rec[['Location','Category','Country','Rating']].head(5)

## step 10:Example Recommendation

In [24]:
recommend_best("kuBZRkVsAR")

        Location  Category    Country  Rating
5058  JKQtkdMKEH     Urban      Egypt    5.00
3319  llNplbsNzk  Cultural  Australia    5.00
2498  PKvzPvaNal  Cultural      Egypt    4.99
3546  oQqSgwqiem  Cultural  Australia    4.99
5885  cgyNjGIqTr    Nature      India    4.99